[2025-02-12T15:51:03.839+0000] {processor.py:157} INFO - Started process (PID=183) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:51:03.840+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T15:51:03.841+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:51:03.841+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:51:03.845+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:51:03.843+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator_dag.py", line 12, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-02-12T15:51:03.845+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:51:03.866+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.030 seconds
[2025-02-12T15:51:34.515+0000] {processor.py:157} INFO - Started process (PID=445) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:51:34.516+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T15:51:34.517+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:51:34.517+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:51:34.522+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:51:34.520+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator_dag.py", line 12, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-02-12T15:51:34.522+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:51:34.542+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.029 seconds
[2025-02-12T15:52:11.384+0000] {processor.py:157} INFO - Started process (PID=706) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:52:11.386+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T15:52:11.387+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:52:11.386+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:52:11.390+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:52:11.389+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator_dag.py", line 12, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-02-12T15:52:11.390+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:52:11.416+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.035 seconds
[2025-02-12T15:52:41.484+0000] {processor.py:157} INFO - Started process (PID=967) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:52:41.486+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T15:52:41.487+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:52:41.486+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:52:41.490+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:52:41.489+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator_dag.py", line 12, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-02-12T15:52:41.490+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:52:41.511+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.030 seconds
[2025-02-12T15:53:11.610+0000] {processor.py:157} INFO - Started process (PID=1234) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:53:11.611+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T15:53:11.612+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:53:11.612+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:53:11.615+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:53:11.614+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator_dag.py", line 12, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-02-12T15:53:11.616+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:53:11.639+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.033 seconds
[2025-02-12T15:53:41.716+0000] {processor.py:157} INFO - Started process (PID=1500) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:53:41.718+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T15:53:41.719+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:53:41.718+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:53:41.722+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:53:41.721+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator_dag.py", line 12, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-02-12T15:53:41.722+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:53:41.744+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.032 seconds
[2025-02-12T15:55:28.100+0000] {processor.py:157} INFO - Started process (PID=184) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:55:28.102+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T15:55:28.102+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:55:28.102+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:55:28.115+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:55:28.468+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:55:28.467+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-02-12T15:55:28.487+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:55:28.486+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-02-12T15:55:28.499+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:55:28.499+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-02-12T15:55:28.500+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:55:28.500+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:transaction_facts_generator' as access control is unset.
[2025-02-12T15:55:28.500+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:55:28.500+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T15:55:28.513+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:55:28.513+0000] {dag.py:2937} INFO - Creating ORM DAG for transaction_facts_generator
[2025-02-12T15:55:28.526+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:55:28.525+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-01-15T17:00:00+00:00, run_after=2025-01-16T17:00:00+00:00
[2025-02-12T15:55:28.543+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.445 seconds
[2025-02-12T15:56:01.801+0000] {processor.py:157} INFO - Started process (PID=445) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:56:01.803+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T15:56:01.804+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:56:01.804+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:56:01.810+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:56:01.829+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:56:01.829+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T15:56:01.849+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:56:01.849+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-01-15T17:00:00+00:00, run_after=2025-01-16T17:00:00+00:00
[2025-02-12T15:56:01.865+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.067 seconds
[2025-02-12T15:56:32.484+0000] {processor.py:157} INFO - Started process (PID=706) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:56:32.486+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T15:56:32.486+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:56:32.486+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:56:32.495+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:56:32.528+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:56:32.528+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T15:56:32.552+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:56:32.551+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-01-15T17:00:00+00:00, run_after=2025-01-16T17:00:00+00:00
[2025-02-12T15:56:32.577+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.097 seconds
[2025-02-12T15:57:03.130+0000] {processor.py:157} INFO - Started process (PID=967) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:57:03.132+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T15:57:03.132+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:57:03.132+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:57:03.140+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:57:03.167+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:57:03.167+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T15:57:03.195+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:57:03.195+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-01-15T17:00:00+00:00, run_after=2025-01-16T17:00:00+00:00
[2025-02-12T15:57:03.217+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.090 seconds
[2025-02-12T15:57:33.502+0000] {processor.py:157} INFO - Started process (PID=1228) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:57:33.505+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T15:57:33.506+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:57:33.506+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:57:33.511+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:57:33.528+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:57:33.528+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T15:57:33.545+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:57:33.544+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-01-15T17:00:00+00:00, run_after=2025-01-16T17:00:00+00:00
[2025-02-12T15:57:33.559+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.059 seconds
[2025-02-12T15:58:04.139+0000] {processor.py:157} INFO - Started process (PID=1506) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:58:04.141+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T15:58:04.142+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:58:04.142+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:58:04.155+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T15:58:22.876+0000] {logging_mixin.py:151} INFO - [2025-02-12T15:58:08.961+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T16:00:02.287+0000] {processor.py:157} INFO - Started process (PID=1827) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:00:02.290+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T16:00:02.291+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:00:02.291+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:00:02.299+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:00:02.496+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:00:02.496+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:transaction_facts_generator' as access control is unset.
[2025-02-12T16:00:02.496+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:00:02.496+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T16:00:02.516+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:00:02.515+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-01-15T17:00:00+00:00, run_after=2025-01-16T17:00:00+00:00
[2025-02-12T16:00:02.538+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.258 seconds
[2025-02-12T16:00:58.846+0000] {processor.py:157} INFO - Started process (PID=2109) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:00:58.849+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T16:00:58.851+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:00:58.850+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:00:58.870+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:02:23.448+0000] {processor.py:157} INFO - Started process (PID=2437) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:02:23.449+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T16:02:23.450+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:02:23.450+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:02:23.459+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:02:23.589+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:02:23.589+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:transaction_facts_generator' as access control is unset.
[2025-02-12T16:02:23.589+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:02:23.589+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T16:02:23.609+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:02:23.609+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-01-15T17:00:00+00:00, run_after=2025-01-16T17:00:00+00:00
[2025-02-12T16:02:23.632+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.187 seconds
[2025-02-12T16:02:53.707+0000] {processor.py:157} INFO - Started process (PID=2699) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:02:53.708+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T16:02:53.709+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:02:53.709+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:02:53.716+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:02:53.737+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:02:53.736+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T16:02:53.767+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:02:53.767+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-01-15T17:00:00+00:00, run_after=2025-01-16T17:00:00+00:00
[2025-02-12T16:02:53.790+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.086 seconds
[2025-02-12T16:03:23.900+0000] {processor.py:157} INFO - Started process (PID=3041) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:03:23.901+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T16:03:23.902+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:03:23.902+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:03:23.909+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:03:23.927+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:03:23.927+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T16:03:23.945+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:03:23.945+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-01-15T17:00:00+00:00, run_after=2025-01-16T17:00:00+00:00
[2025-02-12T16:03:23.963+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.065 seconds
[2025-02-12T16:03:54.136+0000] {processor.py:157} INFO - Started process (PID=3302) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:03:54.137+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T16:03:54.138+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:03:54.138+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:03:54.146+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:03:54.168+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:03:54.168+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T16:03:54.189+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:03:54.188+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-01-15T17:00:00+00:00, run_after=2025-01-16T17:00:00+00:00
[2025-02-12T16:03:54.209+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.076 seconds
[2025-02-12T16:04:24.356+0000] {processor.py:157} INFO - Started process (PID=3563) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:04:24.357+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T16:04:24.357+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:04:24.357+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:04:24.363+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:04:24.380+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:04:24.380+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T16:04:24.397+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:04:24.397+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-01-15T17:00:00+00:00, run_after=2025-01-16T17:00:00+00:00
[2025-02-12T16:04:24.413+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.059 seconds
[2025-02-12T16:04:54.601+0000] {processor.py:157} INFO - Started process (PID=3830) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:04:54.602+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T16:04:54.602+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:04:54.602+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:04:54.608+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:04:54.629+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:04:54.629+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T16:04:54.649+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:04:54.648+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-01-15T17:00:00+00:00, run_after=2025-01-16T17:00:00+00:00
[2025-02-12T16:04:54.664+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.067 seconds
[2025-02-12T16:05:24.745+0000] {processor.py:157} INFO - Started process (PID=4091) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:05:24.746+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T16:05:24.747+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:05:24.746+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:05:24.752+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:05:24.771+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:05:24.771+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T16:05:24.789+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:05:24.789+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-01-15T17:00:00+00:00, run_after=2025-01-16T17:00:00+00:00
[2025-02-12T16:05:24.804+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.062 seconds
[2025-02-12T16:05:55.404+0000] {processor.py:157} INFO - Started process (PID=4358) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:05:55.406+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T16:05:55.406+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:05:55.406+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:05:55.412+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:05:55.429+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:05:55.429+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T16:05:55.446+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:05:55.446+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-01-15T17:00:00+00:00, run_after=2025-01-16T17:00:00+00:00
[2025-02-12T16:05:55.460+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.058 seconds
[2025-02-12T16:06:27.086+0000] {processor.py:157} INFO - Started process (PID=4613) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:06:27.088+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T16:06:27.089+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:06:27.089+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:06:27.095+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:06:27.115+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:06:27.115+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T16:06:27.136+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:06:27.136+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-01-15T17:00:00+00:00, run_after=2025-01-16T17:00:00+00:00
[2025-02-12T16:06:27.157+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.075 seconds
[2025-02-12T16:06:57.253+0000] {processor.py:157} INFO - Started process (PID=4886) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:06:57.255+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T16:06:57.256+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:06:57.256+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:06:57.262+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:06:57.281+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:06:57.281+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T16:06:57.306+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:06:57.305+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-01-15T17:00:00+00:00, run_after=2025-01-16T17:00:00+00:00
[2025-02-12T16:06:57.326+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.076 seconds
[2025-02-12T16:07:27.761+0000] {processor.py:157} INFO - Started process (PID=5156) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:07:27.763+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T16:07:27.764+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:07:27.763+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:07:27.769+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:07:27.789+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:07:27.789+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T16:07:27.809+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:07:27.809+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-01-15T17:00:00+00:00, run_after=2025-01-16T17:00:00+00:00
[2025-02-12T16:07:27.826+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.067 seconds
[2025-02-12T16:07:58.150+0000] {processor.py:157} INFO - Started process (PID=5418) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:07:58.153+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T16:07:58.154+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:07:58.153+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:07:58.159+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:07:58.178+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:07:58.178+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T16:07:58.202+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:07:58.202+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-01-15T17:00:00+00:00, run_after=2025-01-16T17:00:00+00:00
[2025-02-12T16:07:58.222+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.074 seconds
[2025-02-12T16:08:33.326+0000] {processor.py:157} INFO - Started process (PID=5724) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:08:33.330+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T16:08:33.337+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:08:33.334+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:08:34.986+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:08:52.053+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:08:52.052+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T16:08:52.203+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 18.908 seconds
[2025-02-12T16:09:37.482+0000] {processor.py:157} INFO - Started process (PID=6013) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:09:37.493+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T16:09:37.500+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:09:37.494+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:09:37.627+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:10:17.336+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:10:17.335+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T16:10:17.424+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 38.715 seconds
[2025-02-12T16:10:34.860+0000] {processor.py:157} INFO - Started process (PID=6288) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:10:34.862+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T16:10:34.863+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:10:34.862+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:10:34.869+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:10:34.893+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:10:34.892+0000] {taskinstance.py:1937} ERROR - {'DAG Id': 'transaction_facts_generator', 'Task Id': 'generate_txn_fact_data', 'Run Id': 'scheduled__2025-02-01T17:00:00+00:00', 'Hostname': '5879df32f101'}
[2025-02-12T16:10:34.914+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:10:34.913+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=transaction_facts_generator, task_id=generate_txn_fact_data, execution_date=20250201T170000, start_date=20250212T160910, end_date=20250212T161034
[2025-02-12T16:10:34.924+0000] {processor.py:790} INFO - Executed failure callback for <TaskInstance: transaction_facts_generator.generate_txn_fact_data scheduled__2025-02-01T17:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-12T16:10:34.937+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:10:34.936+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T16:10:35.008+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:10:35.007+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-02-11T17:00:00+00:00, run_after=2025-02-12T17:00:00+00:00
[2025-02-12T16:10:35.031+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.173 seconds
[2025-02-12T16:10:44.992+0000] {processor.py:157} INFO - Started process (PID=6297) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:10:44.994+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T16:10:44.995+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:10:44.995+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:10:45.001+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:10:45.026+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:10:45.026+0000] {taskinstance.py:1937} ERROR - {'DAG Id': 'transaction_facts_generator', 'Task Id': 'generate_txn_fact_data', 'Run Id': 'scheduled__2025-01-31T17:00:00+00:00', 'Hostname': '5879df32f101'}
[2025-02-12T16:10:45.048+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:10:45.047+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=transaction_facts_generator, task_id=generate_txn_fact_data, execution_date=20250131T170000, start_date=20250212T160910, end_date=20250212T161045
[2025-02-12T16:10:45.058+0000] {processor.py:790} INFO - Executed failure callback for <TaskInstance: transaction_facts_generator.generate_txn_fact_data scheduled__2025-01-31T17:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-12T16:10:45.061+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:10:45.061+0000] {taskinstance.py:1937} ERROR - {'DAG Id': 'transaction_facts_generator', 'Task Id': 'generate_txn_fact_data', 'Run Id': 'scheduled__2025-02-02T17:00:00+00:00', 'Hostname': '5879df32f101'}
[2025-02-12T16:10:45.070+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:10:45.069+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=transaction_facts_generator, task_id=generate_txn_fact_data, execution_date=20250202T170000, start_date=20250212T160910, end_date=20250212T161045
[2025-02-12T16:10:45.073+0000] {processor.py:790} INFO - Executed failure callback for <TaskInstance: transaction_facts_generator.generate_txn_fact_data scheduled__2025-02-02T17:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-12T16:10:45.075+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:10:45.075+0000] {taskinstance.py:1937} ERROR - {'DAG Id': 'transaction_facts_generator', 'Task Id': 'generate_txn_fact_data', 'Run Id': 'scheduled__2025-01-31T17:00:00+00:00', 'Hostname': '5879df32f101'}
[2025-02-12T16:10:45.082+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:10:45.082+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=transaction_facts_generator, task_id=generate_txn_fact_data, execution_date=20250131T170000, start_date=20250212T160910, end_date=20250212T161045
[2025-02-12T16:10:45.087+0000] {processor.py:790} INFO - Executed failure callback for <TaskInstance: transaction_facts_generator.generate_txn_fact_data scheduled__2025-01-31T17:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-12T16:10:45.100+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:10:45.100+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T16:10:45.118+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:10:45.118+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-02-11T17:00:00+00:00, run_after=2025-02-12T17:00:00+00:00
[2025-02-12T16:10:45.136+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.146 seconds
[2025-02-12T16:11:15.684+0000] {processor.py:157} INFO - Started process (PID=6558) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:11:15.687+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T16:11:15.688+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:11:15.688+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:11:15.694+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:11:15.717+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:11:15.717+0000] {taskinstance.py:1937} ERROR - {'DAG Id': 'transaction_facts_generator', 'Task Id': 'generate_txn_fact_data', 'Run Id': 'scheduled__2025-02-02T17:00:00+00:00', 'Hostname': '5879df32f101'}
[2025-02-12T16:11:15.737+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:11:15.737+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=transaction_facts_generator, task_id=generate_txn_fact_data, execution_date=20250202T170000, start_date=20250212T160910, end_date=20250212T161115
[2025-02-12T16:11:15.745+0000] {processor.py:790} INFO - Executed failure callback for <TaskInstance: transaction_facts_generator.generate_txn_fact_data scheduled__2025-02-02T17:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-12T16:11:15.758+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:11:15.757+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T16:11:15.773+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:11:15.773+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-02-11T17:00:00+00:00, run_after=2025-02-12T17:00:00+00:00
[2025-02-12T16:11:15.796+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.115 seconds
[2025-02-12T16:11:46.217+0000] {processor.py:157} INFO - Started process (PID=6820) to work on /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:11:46.218+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator_dag.py for tasks to queue
[2025-02-12T16:11:46.219+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:11:46.219+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:11:46.226+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator_dag.py
[2025-02-12T16:11:46.248+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:11:46.248+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-02-12T16:11:46.269+0000] {logging_mixin.py:151} INFO - [2025-02-12T16:11:46.268+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-02-11T17:00:00+00:00, run_after=2025-02-12T17:00:00+00:00
[2025-02-12T16:11:46.284+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator_dag.py took 0.070 seconds
